apiVersion: apps/v1
kind: Deployment
metadata:
  name: patient-service
  namespace: healthcare
spec:
  replicas: 1
  selector:
    matchLabels:
      app: patient-service
  template:
    metadata:
      labels:
        app: patient-service
    spec:
      initContainers:
        - name: wait-for-mysql
          image: busybox:1.36
          command: ['sh', '-c', 'until nc -z mysql-patient 3306; do echo waiting for mysql-patient; sleep 3; done']
      containers:
        - name: patient-service
          image: patient-service:1.0
          imagePullPolicy: Never
          ports:
            - containerPort: 8081
          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:mysql://mysql-patient:3306/patientdb?createDatabaseIfNotExist=true
            - name: SPRING_DATASOURCE_USERNAME
              value: root
            - name: SPRING_DATASOURCE_PASSWORD
              value: root
            - name: SPRING_DATASOURCE_DRIVER_CLASS_NAME
              value: com.mysql.cj.jdbc.Driver
            - name: SPRING_JPA_HIBERNATE_DDL_AUTO
              value: update
          readinessProbe:
            httpGet:
              path: /api/patients
              port: 8081
            initialDelaySeconds: 30
            periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: patient-service
  namespace: healthcare
spec:
  selector:
    app: patient-service
  ports:
    - port: 8081
      targetPort: 8081
